// SPDX-License-Identifier: GPL-3.0-only
'use strict';
// What changed, shown once in the window after an update (app.js, whatsNew). Newest first; every version has its
// points in each language. Add the new version's entry here with each release.
const WHATSNEW = [
  { v: '0.3.15',
    en: ['Updates install by themselves: haku checks every few hours and updates when a new version is out, after a notice from the tray (never during a full-screen game or a presentation).'],
    ru: ['Обновления ставятся сами: haku проверяет каждые несколько часов и обновляется, когда выходит новая версия, предупредив уведомлением из трея (никогда во время полноэкранной игры или презентации).'],
    fr: ['Les mises à jour s\'installent toutes seules : haku vérifie toutes les quelques heures et se met à jour quand une nouvelle version sort, après une notification (jamais pendant un jeu en plein écran ou une présentation).'] },
  { v: '0.3.14',
    en: ['Device settings show only what the device can do: an Elgato Key Light or Ring Light gets its colour temperature (2900–7000 K) and brightness, no effects or palettes.',
      'A Govee sync box in its own screen-sync mode shows just how to switch it to haku\'s colours.',
      'Groups no longer push colours or effects onto white-only lights.',
      'This window: after an update haku shows what is new. Open it again under Settings → What is new.'],
    ru: ['В настройках устройства теперь только то, что оно умеет: у Elgato Key Light и Ring Light — температура белого (2900–7000 K) и яркость, без эффектов и палитр.',
      'Для Govee Sync Box в режиме своей синхронизации с экраном — только подсказка, как переключить его на цвета haku.',
      'Группы больше не навязывают цвета и эффекты лампам, которые светят только белым.',
      'Это окно: после обновления haku показывает, что нового. Открыть снова — «Настройки» → «Что нового».'],
    fr: ['Les réglages d\'un appareil ne montrent que ce qu\'il sait faire : une Elgato Key Light ou Ring Light n\'a que sa température de couleur (2900–7000 K) et sa luminosité, sans effets ni palettes.',
      'Une sync box Govee dans son propre mode (synchro écran) indique juste comment passer aux couleurs de haku.',
      'Les groupes n\'imposent plus couleurs ni effets aux lampes qui ne font que du blanc.',
      'Cette fenêtre : après une mise à jour, haku montre les nouveautés. Pour la rouvrir : Réglages → Nouveautés.'] },
  { v: '0.3.13',
    en: ['OpenRGB by itself: PC → Other PC hardware → "Download and set up OpenRGB". haku downloads it, starts it hidden and adds the graphics cards, boards and RAM it finds.',
      'Themes: dark, grey and light (Settings → General → Theme).',
      'French language.'],
    ru: ['OpenRGB сам по себе: «ПК» → «Другое оборудование ПК» → «Скачать и настроить OpenRGB». haku скачивает его, скрыто запускает и добавляет найденные видеокарты, платы и память.',
      'Темы: тёмная, серая и светлая («Настройки» → «Общие» → «Тема»).',
      'Французский язык.'],
    fr: ['OpenRGB tout seul : PC → Autre matériel du PC → « Télécharger et configurer OpenRGB ». haku le télécharge, le lance en arrière-plan et ajoute les cartes graphiques, cartes mères et RAM qu\'il trouve.',
      'Thèmes : sombre, gris et clair (Réglages → Général → Thème).',
      'Langue française.'] },
  { v: '0.3.12',
    en: ['Elgato Key Lights now react (they were found but ignored the commands).',
      'haku checks a list of versions the author has stopped supporting, signed by the author; such a version shows a message with a download link.'],
    ru: ['Elgato Key Light теперь реагируют (раньше находились, но не слушались команд).',
      'haku сверяется со списком версий, которые автор больше не поддерживает (список подписан автором); такая версия показывает сообщение со ссылкой на загрузку.'],
    fr: ['Les Elgato Key Light réagissent enfin (elles étaient trouvées mais ignoraient les commandes).',
      'haku consulte une liste, signée par l\'auteur, des versions qui ne sont plus prises en charge ; une telle version affiche un message avec un lien de téléchargement.'] },
  { v: '0.3.11',
    en: ['The AI colour picker keeps its model in memory only while it works; "Ollama only when needed" keeps Ollama out of Windows startup.',
      'One-click setup of Ollama and the model under Settings.',
      'Divoom Times Gate lights (experimental).'],
    ru: ['Подбор цветов ИИ держит модель в памяти только пока работает; «Ollama только по запросу» убирает Ollama из автозагрузки Windows.',
      'Установка Ollama и модели одной кнопкой в «Настройках».',
      'Подсветка Divoom Times Gate (экспериментально).'],
    fr: ['Le choix des couleurs par IA ne garde son modèle en mémoire que pendant qu\'il travaille ; « Ollama seulement quand il faut » retire Ollama du démarrage de Windows.',
      'Installation d\'Ollama et du modèle en un clic dans les Réglages.',
      'Éclairage du Divoom Times Gate (expérimental).'] },
  { v: '0.3.10',
    en: ['Wooting keyboards directly over USB.'],
    ru: ['Клавиатуры Wooting напрямую по USB.'],
    fr: ['Claviers Wooting directement en USB.'] },
  { v: '0.3.9',
    en: ['Profiles: the whole setup for a scenario (gaming, work, night…), switched above the widgets, from the tray or by hotkey.',
      'Elgato Key Light, Ring Light and Light Strip.'],
    ru: ['Профили: весь набор настроек под сценарий (игра, работа, ночь…), переключение над виджетами, в трее или горячей клавишей.',
      'Elgato Key Light, Ring Light и Light Strip.'],
    fr: ['Profils : toute la configuration d\'un scénario (jeu, travail, nuit…), à changer au-dessus des widgets, depuis la barre des tâches ou par raccourci.',
      'Elgato Key Light, Ring Light et Light Strip.'] },
];
