// SPDX-License-Identifier: GPL-3.0-only
'use strict';
// What changed, shown once in the window after an update (app.js, whatsNew). Newest first; every version has its
// points in each language. Add the new version's entry here with each release.
const WHATSNEW = [
  { v: '0.4.3',
    en: ['A new effect, Colour wave: bands of your colours sweep across the whole room, every device taking the wave as it passes, like SignalRGB\'s Color Wave. Choose the direction (left, right, up, down, from or to the middle) and how long the wave is.'],
    ru: ['Новый эффект «Цветная волна»: полосы ваших цветов идут волной через всю комнату, каждое устройство подхватывает её по очереди, как Color Wave в SignalRGB. Можно выбрать направление (влево, вправо, вверх, вниз, от центра или к центру) и длину волны.'],
    fr: ['Un nouvel effet, Vague de couleurs : des bandes de vos couleurs balaient toute la pièce, chaque appareil prenant la vague à son passage, comme le Color Wave de SignalRGB. Choisissez la direction (gauche, droite, haut, bas, depuis ou vers le centre) et la longueur de la vague.'] },
  { v: '0.4.2',
    en: ['Report a problem, right from the app: Settings → Report a problem. Say what happened, and it goes straight to the developer with the diagnostics (no keys, tokens or passwords). You can leave a way to reach you, and the diagnostics can still be saved as a file instead.'],
    ru: ['Сообщить о проблеме прямо из приложения: Настройки → «Сообщить о проблеме». Опишите, что случилось, и описание сразу уйдёт разработчику вместе с диагностикой (без ключей, токенов и паролей). Можно оставить контакт для ответа, а диагностику по-прежнему можно сохранить файлом.'],
    fr: ['Signalez un problème depuis l\'app : Réglages → Signaler un problème. Dites ce qui s\'est passé, et c\'est envoyé directement au développeur avec le diagnostic (sans clés, jetons ni mots de passe). Vous pouvez laisser un moyen de vous joindre, et le diagnostic peut toujours être enregistré en fichier.'] },
  { v: '0.4.1',
    en: ['Devices through OpenRGB that have no Direct mode (some ASRock graphics cards, for one) no longer just flash: haku lights them in their Static mode, a little slower, or with one colour, and leaves alone the ones it cannot light. The device\'s line says which.',
      'Each OpenRGB device has an Updates setting: if its lights still blink instead of moving smoothly, choose fewer updates per second.'],
    ru: ['Устройства через OpenRGB без режима Direct (например, некоторые видеокарты ASRock) больше не просто мигают: haku светит ими в их режиме Static, чуть медленнее, или одним цветом, а те, которыми управлять нельзя, не трогает. В строке устройства написано, как именно.',
      'У каждого устройства OpenRGB появилась настройка «Обновления»: если подсветка всё равно мигает вместо плавных эффектов, выберите меньше обновлений в секунду.'],
    fr: ['Les appareils passant par OpenRGB sans mode Direct (certaines cartes graphiques ASRock, par exemple) ne font plus que clignoter : haku les éclaire dans leur mode Static, un peu plus lentement, ou d\'une seule couleur, et laisse tranquilles ceux qu\'il ne peut pas éclairer. La ligne de l\'appareil indique lequel.',
      'Chaque appareil OpenRGB a un réglage Mises à jour : si ses lumières clignotent encore au lieu de bouger en douceur, choisissez moins de mises à jour par seconde.'] },
  { v: '0.4.0',
    en: ['haku Pro: the lights on Wi-Fi and the network (Nanoleaf, WLED, Hue, Govee, LIFX, Yeelight, WiZ, Elgato, Divoom, Tuya, AiDot) and phone control are now part of haku Pro, $2 a month or $10 a year. A free 14-day trial starts with this update, and Settings → haku Pro shows how many days are left. The PC\'s own lighting, USB devices, Razer, SteelSeries, Logitech and every effect stay free.',
      'The PC\'s lighting can be given back to the programs it came with (MSI Center, iCUE, Armoury Crate, Synapse...): Its own lighting on a device\'s card, or Give back to their apps on the PC tab (also in the tray menu). Its own effect comes back and haku leaves it alone until you take it again.',
      'Community: a new tab next to Effects and My presets with presets other people shared. Search, sort by popular or new, like, and add one in a click. Your own presets can be published from their Share window.',
      'Backup: Settings can save all of haku\'s setup to one file and bring it back on another PC (passwords and keys stay on this PC). Presets can be shared as a short code.',
      'Home Assistant (haku Pro): haku shows up as a light with its effects and brightness, and a profile picker, through MQTT.'],
    ru: ['haku Pro: лампы по Wi-Fi и в сети (Nanoleaf, WLED, Hue, Govee, LIFX, Yeelight, WiZ, Elgato, Divoom, Tuya, AiDot) и управление с телефона теперь входят в haku Pro — $2 в месяц или $10 в год. С этим обновлением начинается бесплатный пробный период на 14 дней; сколько дней осталось, видно в Настройках → haku Pro. Подсветка самого ПК, USB-устройства, Razer, SteelSeries, Logitech и все эффекты остаются бесплатными.',
      'Подсветку ПК можно вернуть её родным программам (MSI Center, iCUE, Armoury Crate, Synapse...): «Своя подсветка» в карточке устройства или «Вернуть родным программам» на вкладке ПК (и в меню трея). Возвращается её собственный эффект, и haku её не трогает, пока не заберёте обратно.',
      'Сообщество: новая вкладка рядом с «Эффектами» и «Моими пресетами» — пресеты, которыми поделились другие. Поиск, популярные и новые, лайки, добавление в один клик. Свои пресеты можно опубликовать из окна «Поделиться».',
      'Резервная копия: в Настройках можно сохранить всю настройку haku в один файл и восстановить её на другом ПК (пароли и ключи остаются на этом ПК). Пресетами можно делиться коротким кодом.',
      'Home Assistant (haku Pro): haku появляется там как лампа со своими эффектами и яркостью и с выбором профиля, через MQTT.'],
    fr: ['haku Pro : les lumières en Wi-Fi et sur le réseau (Nanoleaf, WLED, Hue, Govee, LIFX, Yeelight, WiZ, Elgato, Divoom, Tuya, AiDot) et le contrôle depuis le téléphone font désormais partie de haku Pro, 2 $ par mois ou 10 $ par an. Un essai gratuit de 14 jours commence avec cette mise à jour, et Réglages → haku Pro indique les jours restants. L\'éclairage du PC lui-même, les appareils USB, Razer, SteelSeries, Logitech et tous les effets restent gratuits.',
      'L\'éclairage du PC peut être rendu aux programmes livrés avec lui (MSI Center, iCUE, Armoury Crate, Synapse...) : Son propre éclairage sur la fiche d\'un appareil, ou Rendre à leurs apps dans l\'onglet PC (aussi dans le menu de la barre des tâches). Son propre effet revient et haku n\'y touche plus jusqu\'à ce que vous le repreniez.',
      'Communauté : un nouvel onglet à côté d\'Effets et Mes préréglages, avec les préréglages partagés par d\'autres. Recherche, populaires ou récents, j\'aime, et ajout en un clic. Vos propres préréglages se publient depuis leur fenêtre Partager.',
      'Sauvegarde : les Réglages enregistrent toute la configuration de haku dans un fichier et la restaurent sur un autre PC (mots de passe et clés restent sur ce PC). Les préréglages se partagent avec un code court.',
      'Home Assistant (haku Pro) : haku y apparaît comme une lumière avec ses effets et sa luminosité, et un choix de profil, via MQTT.'] },
  { v: '0.3.33',
    en: ['The devices in the preview can be put in your own order: choose Arrange in the preview\'s menu and drag a device onto another to swap their places. Dragging outside Arrange still makes a group.',
      'The theme switch in Settings no longer gets cut off when the window is narrow or the hidden themes are open: the buttons move under the label.'],
    ru: ['Устройства в превью можно расставить в своём порядке: выберите «Расставить» в меню превью и перетащите одно устройство на другое, чтобы поменять их местами. Перетаскивание без «Расставить» по-прежнему делает группу.',
      'Переключатель темы в настройках больше не обрезается в узком окне или когда открыты скрытые темы: кнопки переходят под надпись.'],
    fr: ['Les appareils de l\'aperçu se rangent dans votre ordre : choisissez Disposer dans le menu de l\'aperçu et glissez un appareil sur un autre pour les échanger de place. Glisser hors de Disposer crée toujours un groupe.',
      'Le choix du thème dans les Réglages n\'est plus coupé quand la fenêtre est étroite ou que les thèmes cachés sont ouverts : les boutons passent sous le libellé.'] },
  { v: '0.3.32',
    en: ['The hidden theme from 0.3.31 got prettier: its butterflies beat their wings, the light in the corner glows without a dark ring, and its name is written with a brush, stroke after stroke.'],
    ru: ['Скрытая тема из 0.3.31 стала красивее: бабочки машут крыльями, свет в углу светится без тёмного кольца, а её название пишется кистью, черта за чертой.'],
    fr: ['Le thème caché de la 0.3.31 est plus beau : ses papillons battent des ailes, la lumière du coin brille sans anneau sombre et son nom s\'écrit au pinceau, trait après trait.'] },
  { v: '0.3.31',
    en: ['A new hidden theme. Those who have its code will know what to type next to the theme switch.'],
    ru: ['Новая скрытая тема. У кого есть её код, тот знает, что вписать рядом с переключателем темы.'],
    fr: ['Un nouveau thème caché. Ceux qui ont son code savent quoi taper à côté du choix du thème.'] },
  { v: '0.3.30',
    en: ['Razer, SteelSeries and Logitech devices: with Razer Synapse, SteelSeries GG or Logitech G HUB running, Scan network offers their keyboards, mice, headsets and more; add the ones you have. Their own app gets the lighting back when haku lets go. New, so far tried only against stand-ins: reports are welcome.',
      'The effects tab switches between the effects and your own presets, so presets no longer get lost among the effects.',
      'Room for 32 devices instead of 16.'],
    ru: ['Устройства Razer, SteelSeries и Logitech: если запущен Razer Synapse, SteelSeries GG или Logitech G HUB, «Искать в сети» предлагает их клавиатуры, мыши, гарнитуры и другое; добавьте то, что у вас есть. Когда haku их отпускает, подсветку забирает их собственное приложение. Это новое и пока проверено только на имитациях: напишите, как работает.',
      'На вкладке эффектов есть переключатель «Эффекты / Мои пресеты», пресеты больше не теряются среди эффектов.',
      'Можно добавить 32 устройства вместо 16.'],
    fr: ['Appareils Razer, SteelSeries et Logitech : avec Razer Synapse, SteelSeries GG ou Logitech G HUB lancé, Analyser le réseau propose leurs claviers, souris, casques et plus ; ajoutez ceux que vous avez. Leur propre app reprend l\'éclairage quand haku les libère. Nouveau, essayé seulement sur des imitations : vos retours sont bienvenus.',
      'L\'onglet des effets bascule entre les effets et vos préréglages, qui ne se perdent plus parmi les effets.',
      'Place pour 32 appareils au lieu de 16.'] },
  { v: '0.3.29',
    en: ['New effect: Screen (ambilight). The lights follow what is on the screen: strips run around its edges, a Nanoleaf wall or a keyboard shows it as a mosaic, single lights take its average colour. Each device can take another part of the screen; it barely uses the PC.'],
    ru: ['Новый эффект: Экран (эмбилайт). Свет повторяет то, что на экране: ленты идут по его краям, стена Nanoleaf или клавиатура показывают его мозаикой, одиночные лампы берут средний цвет. Каждому устройству можно задать свою часть экрана; ПК почти не нагружается.'],
    fr: ['Nouvel effet : Écran (ambilight). Les lumières suivent ce qui est à l\'écran : les bandes en font le tour, un mur Nanoleaf ou un clavier le montre en mosaïque, les lampes seules prennent sa couleur moyenne. Chaque appareil peut prendre une autre partie de l\'écran ; le PC n\'est presque pas sollicité.'] },
  { v: '0.3.28',
    en: ['Every brand of lights you add gets its own tab in the sidebar, as Nanoleaf has: WLED, Govee, LIFX, Yeelight, Hue, WiZ, Tuya, Elgato, Divoom. PC hardware and finding new devices stay under Devices.'],
    ru: ['У каждого добавленного бренда света теперь своя вкладка в левой панели, как у Nanoleaf: WLED, Govee, LIFX, Yeelight, Hue, WiZ, Tuya, Elgato, Divoom. Железо ПК и поиск новых устройств остаются в «Устройствах».'],
    fr: ['Chaque marque de lumières ajoutée a maintenant son onglet dans la barre latérale, comme Nanoleaf : WLED, Govee, LIFX, Yeelight, Hue, WiZ, Tuya, Elgato, Divoom. Le matériel du PC et la recherche d\'appareils restent dans Appareils.'] },
  { v: '0.3.27',
    en: ['Nanoleaf Shapes triangles are drawn the right way round in the preview (they used to come out turned over), mirrored layouts included.'],
    ru: ['Треугольники Nanoleaf Shapes рисуются в превью правильной стороной (раньше выходили перевёрнутыми), в том числе в зеркальных раскладках.'],
    fr: ['Les triangles Nanoleaf Shapes sont dessinés dans le bon sens dans l\'aperçu (ils sortaient retournés), dispositions en miroir comprises.'] },
  { v: '0.3.26',
    en: ['The PC tab is now on every PC, not only with an MSI board or RGB memory: Lighting in this PC and the OpenRGB set-up are there for any hardware. The Memory and ARGB strip cards show only where that hardware is found.',
      'Clicking the memory or the ARGB strip in the preview opens the right card again.'],
    ru: ['Вкладка «ПК» теперь есть на любом компьютере, а не только с платой MSI или RGB-памятью: «Подсветка в этом ПК» и установка OpenRGB доступны для любого железа. Карточки «Память» и ARGB-ленты показываются, только если такое железо найдено.',
      'Клик по памяти или ARGB-ленте в превью снова открывает нужную карточку.'],
    fr: ['L\'onglet PC est maintenant là sur tous les PC, pas seulement avec une carte mère MSI ou de la mémoire RGB : l\'éclairage de ce PC et l\'installation d\'OpenRGB servent pour tout matériel. Les cartes Mémoire et bande ARGB n\'apparaissent que si ce matériel est trouvé.',
      'Un clic sur la mémoire ou la bande ARGB dans l\'aperçu ouvre de nouveau la bonne carte.'] },
  { v: '0.3.25',
    en: ['Ten new effects: Rainbow, Fire, Ocean, Twinkle, Meteor, Plasma, Aurora, Ripple, Matrix and Candle. They span every device as one picture (Nanoleaf included), each with its own colours, which you can change.',
      'A device\'s own brightness now goes down to 1%, and Elgato Key Lights to 3%, as in Elgato\'s app.'],
    ru: ['Десять новых эффектов: Радуга, Огонь, Океан, Мерцание, Метеор, Плазма, Северное сияние, Капли, Матрица и Свеча. Они идут через все устройства одной картинкой (включая Nanoleaf), у каждого свои цвета, их можно поменять.',
      'Своя яркость устройства теперь опускается до 1%, а у Elgato Key Light — до 3%, как в приложении Elgato.'],
    fr: ['Dix nouveaux effets : Arc-en-ciel, Feu, Océan, Scintillement, Météore, Plasma, Aurore, Gouttes, Matrice et Bougie. Ils parcourent tous les appareils comme une seule image (Nanoleaf compris), chacun avec ses couleurs, modifiables.',
      'La luminosité propre d\'un appareil descend maintenant à 1 %, et les Elgato Key Light à 3 %, comme dans l\'app Elgato.'] },
  { v: '0.3.24',
    en: ['Show in the preview: every device has its own line now, so a graphics card or a lamp can be left out on its own.',
      'After installing or updating by hand, haku\'s window opens by itself (with what is new).',
      'Nanoleaf Shapes: hexagons next to triangles are no longer drawn turned in the preview.'],
    ru: ['«Показывать в превью»: у каждого устройства теперь своя галочка, можно убрать отдельно видеокарту или лампу.',
      'После ручной установки или обновления окно haku открывается само (с «Что нового»).',
      'Nanoleaf Shapes: шестиугольники рядом с треугольниками больше не рисуются повёрнутыми в превью.'],
    fr: ['Afficher dans l\'aperçu : chaque appareil a maintenant sa ligne, une carte graphique ou une lampe peut être retirée seule.',
      'Après une installation ou une mise à jour à la main, la fenêtre de haku s\'ouvre toute seule (avec les nouveautés).',
      'Nanoleaf Shapes : les hexagones à côté de triangles ne sont plus dessinés tournés dans l\'aperçu.'] },
  { v: '0.3.23',
    en: ['Lighting in this PC (PC tab, at the top): haku finds the board, the memory, the graphics cards and the USB lighting devices, and says for each how it is lit: by haku itself, through OpenRGB, or what is still missing (with the button for it).',
      'After an update installed by hand, haku starts by itself again.'],
    ru: ['Подсветка в этом ПК (вкладка «ПК», сверху): haku находит плату, память, видеокарты и USB-устройства с подсветкой и показывает, как подсвечивается каждое: самой haku, через OpenRGB, или чего ещё не хватает (с кнопкой для этого).',
      'После обновления, установленного вручную, haku снова запускается сама.'],
    fr: ['L\'éclairage de ce PC (onglet PC, en haut) : haku trouve la carte mère, la mémoire, les cartes graphiques et les appareils USB éclairés, et dit pour chacun comment il est éclairé : par haku, via OpenRGB, ou ce qui manque encore (avec le bouton pour ça).',
      'Après une mise à jour installée à la main, haku redémarre tout seul.'] },
  { v: '0.3.22',
    en: ['Divoom Times Gate and Times Frame: the screens stay off with the lights (they used to come back on right away).'],
    ru: ['Divoom Times Gate и Times Frame: экраны остаются выключенными вместе со светом (раньше сразу включались обратно).'],
    fr: ['Divoom Times Gate et Times Frame : les écrans restent éteints avec l\'éclairage (ils se rallumaient aussitôt).'] },
  { v: '0.3.21',
    en: ['Divoom Times Frame: its side light follows haku. Pick the light effect by number in its card (they have no names yet).',
      'Divoom Times Frame screen: leave it as it is, show a Divoom dial, or haku\'s own screen with the time, CPU, memory, the effect and the profile. Each profile keeps its own.',
      'Divoom Times Gate and Times Frame: the screens go off with the lights (can be turned off in the device\'s card).'],
    ru: ['Divoom Times Frame: боковая подсветка следует за haku. Эффект подсветки выбирается по номеру в карточке (названий у них пока нет).',
      'Экран Divoom Times Frame: оставить как есть, показать циферблат Divoom или экран haku со временем, CPU, памятью, эффектом и профилем. У каждого профиля свой.',
      'Divoom Times Gate и Times Frame: экраны гаснут вместе со светом (отключается в карточке устройства).'],
    fr: ['Divoom Times Frame : son éclairage latéral suit haku. L\'effet se choisit par numéro dans sa carte (ils n\'ont pas encore de nom).',
      'Écran de la Divoom Times Frame : le laisser tel quel, afficher un cadran Divoom, ou l\'écran de haku avec l\'heure, le CPU, la mémoire, l\'effet et le profil. Chaque profil garde le sien.',
      'Divoom Times Gate et Times Frame : les écrans s\'éteignent avec l\'éclairage (désactivable dans la carte de l\'appareil).'] },
  { v: '0.3.20',
    en: ['Updates keep coming even after "Check now" is pressed many times: GitHub limits how often it may be asked, so haku asks at most once a minute and, when GitHub says no, finds the new version another way.',
      'Divoom Times Frame: haku looks for the command its lights take. If they stay dark, the diagnostics now show what it tried.'],
    ru: ['Обновления приходят, даже если много раз нажать «Проверить»: GitHub ограничивает, как часто его можно спрашивать, поэтому haku спрашивает не чаще раза в минуту, а если GitHub отказал, находит новую версию другим путём.',
      'Divoom Times Frame: haku ищет команду, которую принимает его подсветка. Если она не загорается, в диагностике теперь видно, что было испробовано.'],
    fr: ['Les mises à jour arrivent même après de nombreux « Vérifier » : GitHub limite la fréquence des demandes, alors haku demande au plus une fois par minute et, si GitHub refuse, trouve la nouvelle version autrement.',
      'Divoom Times Frame : haku cherche la commande que prend son éclairage. S\'il reste éteint, le diagnostic montre maintenant ce qui a été essayé.'] },
  { v: '0.3.19',
    en: ['Divoom Times Frame connects (it was wrongly told its LocalToken was wrong).',
      'Divoom devices are found more reliably when Divoom\'s service misses them for a moment.'],
    ru: ['Divoom Times Frame подключается (раньше haku ошибочно писала, что LocalToken неверный).',
      'Устройства Divoom находятся надёжнее, когда сервис Divoom на миг их не видит.'],
    fr: ['La Divoom Times Frame se connecte (haku disait à tort que son LocalToken était faux).',
      'Les appareils Divoom sont trouvés plus sûrement quand le service de Divoom les rate un instant.'] },
  { v: '0.3.18',
    en: ['Divoom Times Gate: the side lights follow haku too. Its card says which lights take haku\'s colours (back and sides, back only, sides only…).',
      'Divoom Times Gate keeps its connection when it misses an answer now and then.',
      'Divoom Times Frame: found and connected, with its own type. Its lights are still being found out: if they stay dark, send the diagnostics.'],
    ru: ['Divoom Times Gate: боковая подсветка тоже следует за haku. В карточке можно выбрать, какая подсветка берёт цвета haku (задняя и боковая, только задняя, только боковая…).',
      'Divoom Times Gate больше не отваливается, когда изредка не отвечает.',
      'Divoom Times Frame находится и подключается, у него свой тип. Его подсветку ещё изучаем: если она не загорается, пришлите диагностику.'],
    fr: ['Divoom Times Gate : l\'éclairage latéral suit haku lui aussi. Sa carte indique quels éclairages prennent les couleurs de haku (arrière et côtés, arrière seul, côtés seuls…).',
      'La Divoom Times Gate garde sa connexion quand elle manque une réponse de temps en temps.',
      'Divoom Times Frame : trouvé et connecté, avec son propre type. Son éclairage est encore à l\'étude : s\'il reste éteint, envoyez le diagnostic.'] },
  { v: '0.3.17',
    en: ['Divoom: a scan finds them (through Divoom\'s own service, like the Divoom app), and a device can be added by its Device ID as well as by its IP. The LocalToken is still needed.',
      'Hidden themes play their animations even when Windows\' animation effects are off (haku\'s own Animations switch still stops them).'],
    ru: ['Divoom: поиск находит их (через сервис самой Divoom, как приложение Divoom), а добавить устройство можно не только по IP, но и по Device ID. LocalToken по-прежнему нужен.',
      'Скрытые темы показывают свои анимации, даже когда в Windows выключены эффекты анимации (переключатель «Анимации» в haku их по-прежнему останавливает).'],
    fr: ['Divoom : une recherche les trouve (via le service de Divoom, comme l\'app Divoom), et un appareil peut être ajouté par son Device ID aussi bien que par son IP. Le LocalToken reste nécessaire.',
      'Les thèmes cachés jouent leurs animations même quand les effets d\'animation de Windows sont désactivés (l\'interrupteur Animations de haku les arrête toujours).'] },
  { v: '0.3.16',
    en: ['Next to the theme switch there is now a field for secret codes. What they open is for you to find out 👀'],
    ru: ['Рядом с выбором темы появилось поле для секретных кодов. Что они открывают — узнаете сами 👀'],
    fr: ['À côté du choix du thème, il y a maintenant un champ pour des codes secrets. Ce qu\'ils ouvrent, à vous de le découvrir 👀'] },
  { v: '0.3.15',
    en: ['Updates install by themselves: haku checks every few hours and updates when a new version is out, after a notice from the tray (never during a full-screen game or a presentation).'],
    ru: ['Обновления ставятся сами: haku проверяет каждые несколько часов и обновляется, когда выходит новая версия, предупредив уведомлением из трея (никогда во время полноэкранной игры или презентации).'],
    fr: ['Les mises à jour s\'installent toutes seules : haku vérifie toutes les quelques heures et se met à jour quand une nouvelle version sort, après une notification (jamais pendant un jeu en plein écran ou une présentation).'] },
  { v: '0.3.14',
    en: ['Device settings show only what the device can do: an Elgato Key Light or Ring Light gets its colour temperature (2900–7000 K) and brightness, no effects or palettes.',
      'A Govee sync box in its own screen-sync mode shows just how to switch it to haku\'s colours.',
      'Groups no longer push colours or effects onto white-only lights.',
      'This window: after an update haku shows what is new. Open it again under Settings → What is new.'],
    ru: ['В настройках устройства теперь только то, что оно умеет: у Elgato Key Light и Ring Light — температура белого (2900–7000 K) и яркость, без эффектов и палитр.',
      'Для Govee Sync Box в режиме своей синхронизации с экраном — только подсказка, как переключить его на цвета haku.',
      'Группы больше не навязывают цвета и эффекты лампам, которые светят только белым.',
      'Это окно: после обновления haku показывает, что нового. Открыть снова — «Настройки» → «Что нового».'],
    fr: ['Les réglages d\'un appareil ne montrent que ce qu\'il sait faire : une Elgato Key Light ou Ring Light n\'a que sa température de couleur (2900–7000 K) et sa luminosité, sans effets ni palettes.',
      'Une sync box Govee dans son propre mode (synchro écran) indique juste comment passer aux couleurs de haku.',
      'Les groupes n\'imposent plus couleurs ni effets aux lampes qui ne font que du blanc.',
      'Cette fenêtre : après une mise à jour, haku montre les nouveautés. Pour la rouvrir : Réglages → Nouveautés.'] },
  { v: '0.3.13',
    en: ['OpenRGB by itself: PC → Other PC hardware → "Download and set up OpenRGB". haku downloads it, starts it hidden and adds the graphics cards, boards and RAM it finds.',
      'Themes: dark, grey and light (Settings → General → Theme).',
      'French language.'],
    ru: ['OpenRGB сам по себе: «ПК» → «Другое оборудование ПК» → «Скачать и настроить OpenRGB». haku скачивает его, скрыто запускает и добавляет найденные видеокарты, платы и память.',
      'Темы: тёмная, серая и светлая («Настройки» → «Общие» → «Тема»).',
      'Французский язык.'],
    fr: ['OpenRGB tout seul : PC → Autre matériel du PC → « Télécharger et configurer OpenRGB ». haku le télécharge, le lance en arrière-plan et ajoute les cartes graphiques, cartes mères et RAM qu\'il trouve.',
      'Thèmes : sombre, gris et clair (Réglages → Général → Thème).',
      'Langue française.'] },
  { v: '0.3.12',
    en: ['Elgato Key Lights now react (they were found but ignored the commands).',
      'haku checks a list of versions the author has stopped supporting, signed by the author; such a version shows a message with a download link.'],
    ru: ['Elgato Key Light теперь реагируют (раньше находились, но не слушались команд).',
      'haku сверяется со списком версий, которые автор больше не поддерживает (список подписан автором); такая версия показывает сообщение со ссылкой на загрузку.'],
    fr: ['Les Elgato Key Light réagissent enfin (elles étaient trouvées mais ignoraient les commandes).',
      'haku consulte une liste, signée par l\'auteur, des versions qui ne sont plus prises en charge ; une telle version affiche un message avec un lien de téléchargement.'] },
  { v: '0.3.11',
    en: ['The AI colour picker keeps its model in memory only while it works; "Ollama only when needed" keeps Ollama out of Windows startup.',
      'One-click setup of Ollama and the model under Settings.',
      'Divoom Times Gate lights (experimental).'],
    ru: ['Подбор цветов ИИ держит модель в памяти только пока работает; «Ollama только по запросу» убирает Ollama из автозагрузки Windows.',
      'Установка Ollama и модели одной кнопкой в «Настройках».',
      'Подсветка Divoom Times Gate (экспериментально).'],
    fr: ['Le choix des couleurs par IA ne garde son modèle en mémoire que pendant qu\'il travaille ; « Ollama seulement quand il faut » retire Ollama du démarrage de Windows.',
      'Installation d\'Ollama et du modèle en un clic dans les Réglages.',
      'Éclairage du Divoom Times Gate (expérimental).'] },
  { v: '0.3.10',
    en: ['Wooting keyboards directly over USB.'],
    ru: ['Клавиатуры Wooting напрямую по USB.'],
    fr: ['Claviers Wooting directement en USB.'] },
  { v: '0.3.9',
    en: ['Profiles: the whole setup for a scenario (gaming, work, night…), switched above the widgets, from the tray or by hotkey.',
      'Elgato Key Light, Ring Light and Light Strip.'],
    ru: ['Профили: весь набор настроек под сценарий (игра, работа, ночь…), переключение над виджетами, в трее или горячей клавишей.',
      'Elgato Key Light, Ring Light и Light Strip.'],
    fr: ['Profils : toute la configuration d\'un scénario (jeu, travail, nuit…), à changer au-dessus des widgets, depuis la barre des tâches ou par raccourci.',
      'Elgato Key Light, Ring Light et Light Strip.'] },
];
